Major Bugfixes. Not yet working

diff --git a/jobs/cephfs/templates/bin/deploy-ceph-post-start.sh.erb b/jobs/cephfs/templates/bin/deploy-ceph-post-start.sh.erb
--- a/jobs/cephfs/templates/bin/deploy-ceph-post-start.sh.erb
+++ b/jobs/cephfs/templates/bin/deploy-ceph-post-start.sh.erb
@@ -10,69 +10,89 @@ ipaddr=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  
 ifcace=$(ifconfig | grep encap:Ethernet | cut -d" " -f1)
 firstadress=<%= (link("ceph-storage").instances.first.address) %>
 clusternodes=<%= (link("ceph-storage").instances) %>
+CLUSTERNODES='<%=
+		clusternodes = link('ceph-storage').instances.map do |instance|
+		{
+			"name" => instance.name,
+			"id" => instance.id,
+			"index" => instance.index,
+			"az" => instance.az,
+			"address" => instance.address
+		}
+		end
+		JSON.dump(clusternodes)
+	%>' 
+ADDRESSES=( $(echo $CLUSTERNODES | jq '.[] | .address') )
+IDS=( $(echo $CLUSTERNODES | jq '.[] | .id') )
 
-if["$ipaddr" == "$firstadress"]; then 	
-	mkdir ~/ceph-cluster && cd ~/ceph-cluster
-	echo "Deploying monitor to $ipaddr"
-	ceph-deploy new $ipaddr #make the admin Node to the Monitor node
+if [ "$ipaddr" == "$firstadress" ]; then 
+	mkdir /home/vcap/ceph-cluster
+	chown vcap:vcap -R /home/vcap/ceph-cluster
+sudo -u vcap bash << EOF
+set -x
+cd /home/vcap/ceph-cluster
+whoami
 
-	if [ ! -e "ceph.conf" ];then
-        echo "Error while deploying monitor. File ceph.conf is missing - Exiting!"
-        exit 1
-	fi
+echo "Deploying monitor to $ipaddr"
+ceph-deploy new $(echo $(echo ${IDS[0]} | sed -e 's/^"//' -e 's/"$//')) #make the admin Node to the Monitor node
 
-	echo "public network = {ipaddr}/{netmask}" >> ceph.conf #todo
+if [ ! -e "ceph.conf" ]; then
+    echo "Error while deploying monitor. File ceph.conf is missing - Exiting!"
+    exit 1
+fi
 
-	for clusternode in "${clusternodes[@]}"
-	do
-	 ceph-deploy install $clusternodes
-	done	
 
-	ceph-deploy mon create-initial
+for hostname in "${IDS[@]}"
+do
+ceph-deploy install $(echo $(echo $hostname| sed -e 's/^"//' -e 's/"$//'))
+done	
 
-	if [ ! -e "ceph.client.admin.keyring" ] && [ ! -e "ceph.bootstrap-mgr.keyring" ] ;then
-        echo "Error while creating initial monitor. keyring missing. Exiting!"
-        exit 1
-	fi
+ceph-deploy mon create-initial
 
-	for clusternode in "${clusternodes[@]}"
-	do
-	 ceph-deploy admin $clusternode
-	done	
+if [ ! -e "ceph.client.admin.keyring" ] || [ ! -e "ceph.bootstrap-mgr.keyring" ]; then
+	echo "Error while creating initial monitor. keyring missing. Exiting!"
+    exit 1
+fi
 
-	for clusternode in "${clusternodes[@]}"
-	do
-	 ceph-deploy admin $clusternode
-	done	
+for hostname in "${IDS[@]}"
+do
+ceph-deploy admin $(echo $(echo $hostname| sed -e 's/^"//' -e 's/"$//'))
+done	
+EOF
 
 	##Creating OSDS
 
-
 	diskfile=$(sudo lsblk | grep /var/vcap/store |  cut -d" " -f1 | sed 's/^..//' | sed 's/.$//')
+sudo -u vcap bash << EOF
+set -x
+cd /home/vcap/ceph-cluster
+for hostname in "${IDS[@]}"
+do
+ ceph-deploy disk zap $(echo $(echo $hostname| sed -e 's/^"//' -e 's/"$//')):$diskfile
+ ceph-deploy osd prepare $(echo $(echo $hostname| sed -e 's/^"//' -e 's/"$//')):$diskfile
+ ceph-deploy osd activate $(echo $(echo $hostname| sed -e 's/^"//' -e 's/"$//')):$diskfile
+done	
 
-	for clusternode in "${clusternodes[@]}"
-	do
-	 ceph-deploy disk zap $clusternode:$diskfile
-	 ceph-deploy osd prepare $clusternode:$diskfile
-	 ceph-deploy osd activate $clusternode:$diskfile
-	done	
-
+EOF
 
 	ceph health > /var/vcap/sys/log/cephfs/health
 
 	#Creating Metadata Server 
 	##We choose the Second Server of our cluster to be the Metada Server
+sudo -u vcap bash << EOF
+set -x
+cd /home/vcap/ceph-cluster
+ceph-deploy mds create $(echo $(echo $${IDS[1]}| sed -e 's/^"//' -e 's/"$//'))
+ceph-deploy install ceph-client
 
-	ceph-deploy mds create ${clusternodes[1]}
-	ceph-deploy install ceph-client
+#Deploy CephFS
+##Create OSD Pools
 
-	#Deploy CephFS
-	##Create OSD Pools
-
-	ceph osd pool create cephfs_data 128
-	ceph osd pool create cephfs_metadata 128
-	ceph fs new cephfs cephfs_metadata cephfs_data
-	ceph mds stat
+ceph osd pool create cephfs_data 128
+ceph osd pool create cephfs_metadata 128
+ceph fs new cephfs cephfs_metadata cephfs_data
+ceph mds stat
+EOF
 fi	
 
 
